tap 'homebrew/core'
tap "homebrew/bundle"

### *nix Utilities ###
# Check spelling programmatically
brew "aspell"
brew "bash"
# GNU core utilities
brew "coreutils"
brew "curl"
# GNU sed
brew "gnu-sed"
# GNU tar
brew "gnu-tar"
# GNU grep
brew "grep"
brew "htop"
brew "logrotate"
# GNU netcat
brew "netcat"
# 7z
brew "p7zip"
# Linting for bash scripts
brew "shfmt"
# More linting for bash scripts
brew "shellcheck"
# Useful utility for file exploration
brew "tree"
# Alternative to while true; do;
brew "watch"
# GNU wget
brew "wget"

### AWS ###
brew "awscli"
# Used by AWS to connect to instances w/o SSH key
cask "session-manager-plugin"

### Google Cloud ###
cask "google-cloud-sdk"

### Cloud Agnostic Utilities ###
brew "packer"
brew "terraform"
brew "terraform-docs"
brew "terragrunt"
brew "tflint"
brew "serverless"

### Config Management ###
brew "ansible"
# Used to create and run tests for ansible
brew "molecule"

### Containers ###
cask "docker"
brew "helm"
brew "kubectl"
# Lightweight utility to set up k3s
# on any local or remote VM.
brew "k3sup"

### General Development Tools ###
# Additional functionality for managing brew via Brewfile
tap 'rcmdnk/file'
brew "brew-file"
# Tool for debugging GRPC
cask "bloomrpc"
brew "colordiff"
# Alternative to postman
cask "insomnia"
cask "iterm2"
# Terminal autocomplete
cask "fig"
# GitHub CLI
brew "gh"
brew "git"
# CLI tool to interact with JSON
brew "jq"
# CLI tool for the Mac App Store
# https://github.com/mas-cli/mas
brew "mas"
brew "mysql-client"
# Useful for API testing
cask "postman"
brew "pre-commit"
# Keyboard shortcuts for modifying the screen layout
cask "rectangle"
# Useful for mongo stuff
cask "robo-3t"
cask "scroll-reverser"
brew "tmux"
cask "vagrant"
brew "vim"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
# Install different versions of xcode
brew "xcinfo"
# Used to run various GUI utilities
cask "xquartz"
brew "yamllint"
# CLI tool to interact with YAML
brew "yq"

### Android ###
brew "apktool"
# Dex to java decompiler -
# used for android security work
brew "jadx"

### Bash ###
# Linting and pre-commit hooks
brew "shfmt"
brew "shellcheck"

### JS  ###
brew "node"

### Go ###
brew "go"

### Python ###
brew "xz"
brew "pyenv"
brew "pipenv"
brew "pylint"

### Web Browsers ###
cask "chromium"
cask "firefox"
cask "google-chrome"

### Chat Apps ###
cask "discord"
# always upgrade auto-updated or unversioned
# messenger cask to latest version -
# even if already installed
cask "messenger", greedy: true
cask "signal"
cask "slack"

### Entertainment ###
cask "spotify"

### Security tools ###
# Great recon tool
tap "caffix/amass"
brew "amass"
# Monitor for persistent components
cask "blockblock"
# Static Code Analysis for IaC
brew "checkov"
# Interact with and manipulate metadata
brew "exiftool"
# Exploit DB CLI - causes a lot of issues with AV and EDR, so it's disabled by default
#brew "exploitdb"
# Find new domains associated with a target
brew "findomain"
# Keeper Desktop Client
cask "keeper-password-manager"
# Notification when a persistent component is added
cask "knockknock"
# Useful for finding things in pdfs
brew "pdfgrep"
# Network monitor
cask "netiquette"
brew "nmap"
# Notify when mic or webcam are activated - can cause issues, so it's disabled by default
# cask "oversight"
# MAC address spoofing
brew "spoof-mac"
brew "sqlmap"
brew "wireshark"
# One of the best static code analysis tools out there
brew "semgrep"
