---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: detect-private-key
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.33.0
    hooks:
      - id: yamllint
        entry: yamllint --strict -c .hooks/linters/yamllint.yaml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        entry: codespell -q 3 -f --skip=".git,.github,magefiles/go.*" README.md

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: script-must-have-extension
        name: Ensure shell scripts end with .sh
        types: [shell]
      - id: shellcheck
      - id: shfmt
      # Configuration in .mdlrc and .hooks/linters/mdstyle.rb
      - id: markdownlint

  - repo: local
    hooks:
      - id: prettier
        name: Run prettier
        entry: .hooks/prettier-hook.sh
        language: script
        types: [json, yaml]
