trigger:
- master

schedules:
- cron: "0 0 * * 0"
  displayName: Weekly midnight (UTC) build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: 'macOS-10.14'

steps:
- script: |
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  displayName: 'Install Homebrew and brew bundle'
  
- script: |
    # These steps need to be done to install awscli without any errors
    rm '/usr/local/bin/aws'
    rm '/usr/local/bin/aws_completer'
    rm '/usr/local/bin/2to3'
    # End annoying steps
    brew bundle
  displayName: 'Install dependencies from Brewfile'
