---
name: Pre-commit
on:
  pull_request:
  push:
    branches: [main]
  # Run this on every release so new release can have
  # updated version
  release:
    types:
      - published
  # on demand
  workflow_dispatch:

env:
  HOMEBREW_BREWFILE: ${{ github.workspace }}/Brewfile
  HOMEBREW_BUNDLE_MAS_SKIP: true
  HOMEBREW_BUNDLE_WHALEBREW_SKIP: true
  HOMEBREW_NO_INSTALL_CLEANUP: true

jobs:
  auto-update:
    name: Update pre-commit hooks
    runs-on: macos-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install shfmt
        run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

      - name: Install shellcheck
        run: brew install shellcheck

      - name: Install Homebrew-file
        run: brew install rcmdnk/file/brew-file

      - name: Remove problematic pre-installed artifacts
        run: |
          # For aws
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
          # For go
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt

      - name: Install, update, and run pre-commit hooks
        run: |
          brew install pre-commit
          pre-commit autoupdate

      - name: Create Pull Request with updates
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/pre-commit-hooks
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
