---
name: brewfile tests
on:
  pull_request:
  push:
    branches:
      - main

  # Run once a week (see https://crontab.guru)
  schedule:
    - cron: "0 0 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com

env:
  HOMEBREW_BREWFILE: ${{ github.workspace }}/Brewfile
  HOMEBREW_BUNDLE_MAS_SKIP: true
  HOMEBREW_BUNDLE_WHALEBREW_SKIP: true
  HOMEBREW_NO_INSTALL_CLEANUP: true

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Set up git repository
        uses: actions/checkout@v3.5.2

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install brew dependencies
        run: brew install shellcheck rcmdnk/file/brew-file pre-commit bats-core

  brewfile_test:
    needs: setup
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Set up Go
        uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4
        with:
          go-version: "1.20"

      - name: Install go module dependencies
        run: |
          go install mvdan.cc/sh/v3/cmd/shfmt@latest
          go install github.com/magefile/mage@latest

      - name: Remove problematic pre-installed artifacts and conflict binaries
        run: |
          # For aws
          rm /usr/local/bin/aws
          rm /usr/local/bin/aws_completer
          # For go
          rm /usr/local/bin/go
          rm /usr/local/bin/gofmt

      - name: Test Brewfile
        run: |
          mage setup
          mage update
          mage run
