---
name: Test Brewfile
on:
  push:
    branches:
      - main

  # Run once a week (see https://crontab.guru)
  schedule:
    - cron: '0 0 * * 0'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      git_user:
        description: Username to associate with running this action
        required: true
        default: Jayson Grace
      git_email:
        description: Email to associate with running this action
        required: true
        default: jayson.e.grace@gmail.com
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: true
        default: false

jobs:
    test:
      name: Build and configure the Brewfile test environment
      runs-on: macos-latest
      steps:
        - name: Set up git repository
          uses: actions/checkout@v2

        - name: Set up Homebrew
          uses: Homebrew/actions/setup-homebrew@master

        - name: Removing existing components to avoid erroring out
          run: |
            # For aws
            rm /usr/local/bin/aws
            rm /usr/local/bin/aws_completer
            # For git
            #rm -rf /usr/local/share/doc/git*
            #rm -rf /usr/local/share/git*
            # For go
            rm /usr/local/bin/go
            rm /usr/local/bin/gofmt
            
        - name: Test Brewfile
          run: brew bundle

        # - name: Setup tmate session if any part of the action fails
        #   if: ${{ failure() }}
        #   uses: mxschmitt/action-tmate@v3
        
